"""
Reads prediction_logs.csv (generated by FastAPI) and
creates a WhyLogs profile for the current production data.
"""

import whylogs as why
import pandas as pd
from pathlib import Path


LOG_PATH = Path("app/prediction_logs.csv")
OUTPUT_PROFILE = Path("monitoring/current_profile.bin")

COLUMN_NAMES = [
    "timestamp",
    "hour",
    "dayofyear",
    "dayofweek",
    "lag_1",
    "lag_2",
    "lag_3",
    "lag_4",
    "prediction"
]

def main():
    if not LOG_PATH.exists():
        raise FileNotFoundError(f"No production logs found at: {LOG_PATH}")

    print("Loading production logs...")
    df = pd.read_csv(LOG_PATH, names=COLUMN_NAMES)

    # Remove the timestamp for drift comparison — it's not a feature
    df = df.drop(columns=["timestamp"])

    print("Generating WhyLogs current profile...")
    profile = why.log(df).profile

    OUTPUT_PROFILE.parent.mkdir(exist_ok=True, parents=True)
    profile.write(str(OUTPUT_PROFILE))

    print(f"Current profile saved to: {OUTPUT_PROFILE}")

if __name__ == "__main__":
    main()
